# Generated by Django 4.0.5 on 2022-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_event_organiser_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='original_list_price',
            field=models.FloatField(default=10),
        ),
    ]
